name: cd

on:
  push:
    branches: [main]

jobs:
  tests:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Add Go bin to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Build app
        run: ./scripts/buildprod.sh

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: GoogleCloud Build
        run: gcloud builds submit --tag us-central1-docker.pkg.dev/peaceful-harbor-462009-t4/notely-ar-repo/notely:latest .